version: '3.8'

services: 
  webapp:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "8081:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development  # Thêm dòng này để bật chế độ phát triển
        - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=postgres;Database=SaleHair
      depends_on:
        - db
      networks:
        - postgres-network
      
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - D:/Workspace/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
